//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyRapPhim
{


    public partial class AdminDashboard
    {
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divRevenueCard;
        protected global::System.Web.UI.WebControls.Label lblDoanhThu;
        protected global::System.Web.UI.WebControls.Label lblSoVe;
        protected global::System.Web.UI.WebControls.Label lblSoPhim;
        protected global::System.Web.UI.WebControls.Label lblSoTaiKhoan;
        protected global::System.Web.UI.WebControls.Repeater rptTopPhimAdmin;
        protected global::System.Web.UI.WebControls.Repeater rptTopPhimStaff;
        protected global::System.Web.UI.WebControls.Panel pnlTopPhimEmpty;
        protected global::System.Web.UI.WebControls.Label lblHomNay;
        protected global::System.Web.UI.WebControls.Repeater rptLichChieu;
        protected global::System.Web.UI.WebControls.Panel pnlLichEmpty;
        protected global::System.Web.UI.WebControls.Repeater rptDatVeAdmin;
        protected global::System.Web.UI.WebControls.Repeater rptDatVeStaff;
        protected global::System.Web.UI.WebControls.Panel pnlDatVeEmpty;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divPhongChieuPanel;
        protected global::System.Web.UI.WebControls.Repeater rptPhongChieu;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divTaiKhoanPanel;
        protected global::System.Web.UI.WebControls.Repeater rptTaiKhoan;

    }
}
