//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyRapPhim
{


    public partial class DoiMatKhau
    {
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.TextBox txtMatKhauCu;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCu;
        protected global::System.Web.UI.WebControls.TextBox txtMatKhauMoi;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvMoi;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revMoi;
        protected global::System.Web.UI.WebControls.TextBox txtXacNhan;
        protected global::System.Web.UI.WebControls.CompareValidator cvXacNhan;
        protected global::System.Web.UI.WebControls.Button btnDoi;
    }
}
