//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyRapPhim
{


    public partial class Phim
    {

        /// <summary>
        /// DataList1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DataList DataList1;

        /// <summary>
        /// txtTimKiem control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTimKiem;

        /// <summary>
        /// btnTimKiem control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnTimKiem;

        /// <summary>
        /// btnXoaTim control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnXoaTim;

        /// <summary>
        /// lblKetQua control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblKetQua;

        /// <summary>
        /// lblKhongCoPhim control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblKhongCoPhim;
    }
}

