//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyRapPhim
{


    public partial class QuanLyPhongChieu
    {
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.Label lblFormTitle;
        protected global::System.Web.UI.WebControls.HiddenField hdnMaPhong;
        protected global::System.Web.UI.WebControls.TextBox txtTenPhong;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTenPhong;
        protected global::System.Web.UI.WebControls.TextBox txtSucChua;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvSucChua;
        protected global::System.Web.UI.WebControls.CompareValidator cvSucChua;
        protected global::System.Web.UI.WebControls.Button btnSavePhong;
        protected global::System.Web.UI.WebControls.Button btnCancelPhong;
        protected global::System.Web.UI.WebControls.GridView gvPhong;
        protected global::System.Web.UI.WebControls.Panel pnlGhe;
        protected global::System.Web.UI.WebControls.Label lblTenPhongGhe;
        protected global::System.Web.UI.WebControls.HiddenField hdnMaPhongGhe;
        protected global::System.Web.UI.WebControls.TextBox txtSoHang;
        protected global::System.Web.UI.WebControls.CompareValidator cvSoHang;
        protected global::System.Web.UI.WebControls.TextBox txtSoGheMoiHang;
        protected global::System.Web.UI.WebControls.CompareValidator cvSoGhe;
        protected global::System.Web.UI.WebControls.DropDownList ddlLoaiGhe;
        protected global::System.Web.UI.WebControls.Button btnSinhGhe;
        protected global::System.Web.UI.WebControls.Button btnXoaTatCaGhe;
        protected global::System.Web.UI.WebControls.Button btnDongGhe;
        protected global::System.Web.UI.WebControls.GridView gvGhe;
    }
}
