//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyRapPhim
{


    public partial class QuanLyNguoiDung
    {
        protected global::System.Web.UI.WebControls.Label lblFormTitle;
        protected global::System.Web.UI.WebControls.HiddenField hdnMaNguoiDung;
        protected global::System.Web.UI.WebControls.TextBox txtHoTen;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvHoTen;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;
        protected global::System.Web.UI.WebControls.TextBox txtSoDienThoai;
        protected global::System.Web.UI.WebControls.TextBox txtMatKhau;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvMatKhau;
        protected global::System.Web.UI.WebControls.DropDownList ddlVaiTro;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.GridView gvNguoiDung;
    }
}
