//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyRapPhim
{


    public partial class QuanLyLichChieu
    {
        protected global::System.Web.UI.WebControls.Label lblFormTitle;
        protected global::System.Web.UI.WebControls.HiddenField hdnMaLichChieu;
        protected global::System.Web.UI.WebControls.DropDownList ddlPhim;
        protected global::System.Web.UI.WebControls.DropDownList ddlPhong;
        protected global::System.Web.UI.WebControls.TextBox txtNgayChieu;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNgay;
        protected global::System.Web.UI.WebControls.TextBox txtGioBatDau;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvGio;
        protected global::System.Web.UI.WebControls.TextBox txtGiaVe;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvGia;
        protected global::System.Web.UI.WebControls.CompareValidator cvGia;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.GridView gvLichChieu;
    }
}
